const inventory_data = 
[
    {
        "inventory_id": "BAK0001",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "SUB JUMBO JR 2-PLY TOILET PAPER",
        "system_par": 3,
        "pack": 8,
        "size": 1000,
        "measurement": "FT",
        "uom": "CS",
        "case_": 4,
        "ea": 3,
        "lb": 5,
        "oz": 4,
        "bag": 6,
        "gal": 1,
        "tray": 9,
        "sleeves": 8,
        "on_hand": 1,
        "open_orders": 5,
        "adjusted_par": 5,
        "adjusted_order": 5,
        "order_": 6,
        "total_case": 9,
        "updated_date": "2023-07-05T23:00:00.000Z"
    },
    {
        "inventory_id": "BAK0002",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "ALMOND SLICED",
        "system_par": 1,
        "pack": 6,
        "size": 2,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0003",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "SUGAR CANE RAW",
        "system_par": 1,
        "pack": 12,
        "size": 1.5,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0004",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "PAN COATING OLIVE OIL SPRAY",
        "system_par": 1,
        "pack": 6,
        "size": 21,
        "measurement": "OZ",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0005",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "PAN COATING ARSL ALL-PUR",
        "system_par": 1,
        "pack": 12,
        "size": 14,
        "measurement": "OZ",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0006",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "LINER TRAY BAKERS (BROWN)",
        "system_par": 2,
        "pack": 1,
        "size": 1000,
        "measurement": "CT",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0007",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "COVER BAKERS RACK",
        "system_par": 2,
        "pack": 1,
        "size": 50,
        "measurement": "CT",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0008",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "CUP MUFFINE LINER",
        "system_par": 0.5,
        "pack": 1,
        "size": 1000,
        "measurement": "CT",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0009",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "SALT SEA-EXTRA COURSE",
        "system_par": 1,
        "pack": 1,
        "size": 10,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0010",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "TOPPING CINNAMON SUGAR",
        "system_par": 1,
        "pack": 1,
        "size": 10,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0011",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "CHOC DARK CONFECT SNAPS CALBAUT",
        "system_par": 2,
        "pack": 12,
        "size": 16,
        "measurement": "OZ",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0012",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "BAG LOAF PFC FREE",
        "system_par": 0,
        "pack": 1,
        "size": 500,
        "measurement": "CT",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0013",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "CEREAL ROLLED OAT REG",
        "system_par": 1,
        "pack": 1,
        "size": 10,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0014",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "SUGAR CONFECTIONER 10X",
        "system_par": 1,
        "pack": 12,
        "size": 2,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    },
    {
        "inventory_id": "BAK0015",
        "created_date": "2023-07-05T23:00:00.000Z",
        "location_": "BAKERS AREA",
        "shop": "PANERA BREAD",
        "description": "TOPPING MINI CHOC CANDIES",
        "system_par": 1,
        "pack": 1,
        "size": 15,
        "measurement": "LB",
        "uom": "CS",
        "case_": 0,
        "ea": 0,
        "lb": 0,
        "oz": 0,
        "bag": 0,
        "gal": 0,
        "tray": 0,
        "sleeves": 0,
        "on_hand": 0,
        "open_orders": 0,
        "adjusted_par": 0,
        "adjusted_order": null,
        "order_": 0,
        "total_case": 0,
        "updated_date": null
    }
]
export {inventory_data};


/*
LB, GAL, OZ : Lock BAG, TRAY, EA, SLEEVES
and the other way round
*/